name: hook:run:ie11

on:
  issue_comment:
    types: [created]

jobs:
  run-ie11:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/run:ie11')
    runs-on: ubuntu-latest
    steps:
      - name: get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
      - run: yarn install --no-lockfile --silent
      - id: test
        run: |
          build=$(yarn build)
          build="${build//$'\n'/\\n}"
          echo "::set-output name=build::$build\n"
        continue-on-error: true
      - run: echo ${{ steps.test.outputs.build }}
      - name: Success message
        uses: actions/github-script@0.9.0
        if: steps.test.outputs.exitcode == 0
        env:
          STDOUT: "```${{join(steps.test.outputs.*, '\n')}}```"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "#### `yarn build` succeed\n" + process.env.STDOUT
            })
