name: hook:run:ie11

on:
  issue_comment:
    types: [created]
defaults:
  run:
    shell: bash

jobs:
  run-ie11:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/run:ie11')
    runs-on: windows-latest
    steps:
      - name: get upstream branch
        id: upstreambranch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
      - run: yarn install --no-lockfile --silent
      - id: test
        run: |
          tmpfile=err.$$
          stdout=$(yarn build 2>$tmpfile)
          stderr=$(cat $tmpfile)
          rm -f $tmpfile
          echo stdout=$stdout stderr=$stderr

          stdout="${stdout//'%'/'%25'}"
          stdout="${stdout//$'\n'/'%0A'}"
          stdout="${stdout//$'\r'/'%0D'}"

          stderr="${stderr//'%'/'%25'}"
          stderr="${stderr//$'\n'/'%0A'}"
          stderr="${stderr//$'\r'/'%0D'}"
          echo "::set-output name=stdout::$stdout"
          echo "::set-output name=stderr::$stderr"
        continue-on-error: true
        shell: bash
      - name: Send a message
        uses: actions/github-script@0.9.0
        env:
          STDOUT: "```\n${{ steps.test.outputs.stdout }}\n${{ steps.test.outputs.stderr }}\n```"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "#### `yarn build`\n" + process.env.STDOUT
            })
