name: comment hook

on:
  issue_comment:
    types: [created]

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch workflow
        run: |
          PAYLOAD=$(cat "$GITHUB_EVENT_PATH")
          NUMBER=$(echo "$PAYLOAD" | jq -c '.issue.number')

          if [[ "$(echo "$PAYLOAD" | jq -c '.issue.pull_request')" = "null" ]]; then
            echo "It's not pull request. Skip it."
            exit 0
          fi

          PULL_REQUEST=$(gh api "repos/$GITHUB_REPOSITORY/pulls/$NUMBER")

          if [[ "$(echo "$PAYLOAD" | jq -c '.comment.body | test("run:ie11"; "i")')" = "true" ]]; then
            gh api "repos/$GITHUB_REPOSITORY/issues/$NUMBER/comments" -F "body=ビルドを実行します :rocket:"

            gh api "repos/$GITHUB_REPOSITORY/actions/workflows/test.yaml/dispatches" -F "ref=$( echo "$PULL_REQUEST" | jq -r '.head.ref')"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.USERS_GITHUB_TOKEN }}
